name: 'EAS Build'
description: 'An action for handling logic when building with EAS'
inputs:
  platform:
    description: 'ios, android, or all'
    required: false
    default: 'all'
  expo-profile:
    description: 'expo profile to use for build'
    required: false
    default: 'production'
  auto-submit:
    description: 'flag for whether or not the build should be auto-submitted to app store/play store'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - run: eas build --platform ${{github.event.inputs.platform}} --profile ${{github.event.inputs.expo-profile}} --non-interactive --no-wait --auto-submit
      if: ${{ github.event.inputs.auto-submit == true }}
      shell: bash
    - run: eas build --platform ${{github.event.inputs.platform}} --profile ${{github.event.inputs.expo-profile}} --non-interactive --no-wait
      if: ${{ github.event.inputs.auto-submit != true }}
      shell: bash