name: 'EAS Build'
description: 'An action for handling logic when building with EAS'
inputs:
  release-stage:
    description: 'alpha, beta or production release (alpha does not upload to TestFlight)'
    required: true
    default: 'alpha'
  platform:
    description: 'ios, android, or all'
    required: true
    default: 'all'
runs:
  using: "composite"
  steps:
    - run: eas build --platform ${{github.event.inputs.platform}} --profile ${{ github.event.inputs.releaseStage }} --non-interactive --no-wait --auto-submit
      if: ${{ github.event.inputs.releaseStage == 'beta' || github.event.inputs.releaseStage == 'production' }}
      shell: bash
    - run: eas build --platform ${{github.event.inputs.platform}} --profile ${{ github.event.inputs.releaseStage }} --non-interactive --no-wait
      if: ${{ github.event.inputs.releaseStage == 'alpha' }}
      shell: bash